### ISSUE TITLE
Archive on zenodo

### ISSUE THREAD

**Issue by KirstieJane** [SarahMorgan/Morphometric_Similarity_SZ#2]
Hey @SarahMorgan! It would be great to have this archived on zenodo so that the exact version of the code is saved (just in case you make any forward changes to this repository), so it is archived properly (github could disappear or you could delete the repo!) and so it can be cited appropriately.

There's a guide here: https://guides.github.com/activities/citable-code

Let me know if you need any help. Would be super easy to jump on a 20 minute skype call to do together 😄

**Comment by SarahMorgan** [comment]
Thanks @KirstieJane ! I'll look into it.

**Comment by SarahMorgan** [comment]
Done, thanks @KirstieJane !
